CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Atlantic_Salmon            GDGDCTVMTLPEVRGPLYVDVPLGPFHYPLEGLLTPEASPGKQPGLSFFSLERERDKERA
Fathead_Minnow             GDGDCTVMTLPEVRGPLYVDVPHGPLPYPPEGLLTPEASPGKQPSLPFFSSLREREKERT
Zebrafish                  GDGDCTVMTLPEVRGPLYVDVPHGPLPYPPEGLLTPEASPGKQPSLPFFSSLRDREKERT
Common_Carp                GDGDCTVMTLPEVRGPLYVDVPHGPLPFPPEGLLTPEASPGKQPSLPFFSSLREREKERM
Ray_Finned_Fish            GDGDCTVMTLPEVHGPLYVDVPHGPLPYPPEGLLTPEASPGKQPSLPFFSSLREREKERT
Channel_Catfish            GDGDCTVMSLPEVRGPLYVDVPYGPLPYPPEGLLTPETSPGKQPSLSFFSLEQEREKERT
Mexican_TetraAstyanax      GDGDCTIMTLPEVRGPLYVDVPHGPLPYPPEGLLTPEASPGKQPTLSFFSL--DREKERT
Red_Bellied_Piranha        GDGDCTIMTLPEVRGPLYVDVPHGPLPYPPEGLLTPEASPGKQPSLSFFSLEREREKERT
                           ******:*:****.******** **: :* *******:****** *.***   :*:*** 

Atlantic_Salmon            EISLLAQHISSLAEGFYLDPLLSKLSPPSMSPSSSPPPPTLSPSVATAGVDSIHMLGEFY
Fathead_Minnow             EISLLAQHISTLAEGFYLDPFLAKLVPSTISERSQ------SPSLNSAGLDTVPLLGEFY
Zebrafish                  EISLLAQHISTLAEGFYLDPLLAKLVPSTLSEHSQ------SP--DSDGLDSIPLLGEFY
Common_Carp                EISLLAQHISTLVEGFYLDPLLTKLVPSTISERSQ------SPSLDSAGTDSIPLLGEFY
Ray_Finned_Fish            EISLLAQHISTLVEGFYLDPLLTKLVPSTISERSQ------SPSLDSAGFDSLPLLGEFY
Channel_Catfish            EISLLAHHISTLAEGFYLDPLLSKLLPSPISPQLS------SPSPDLEGPETISLQGEFY
Mexican_TetraAstyanax      EISLLAQHISTLAEGFYLDPLLSKLLPSSISPRAP------SPSLDSVGLETISLLGEIY
Red_Bellied_Piranha        EISLLAQHISTLAEGFYLDPFLSKLLPSSVSPQPP------SPSLDSVGLETVSLLGEFY
                           ******:***:*.*******:*:** *..:*          **     * ::: : **:*

Atlantic_Salmon            PVKVWKGLDFPVFQDDDDSLFEESILEALLQDFSAPPPLSPSIS-------PSSPPNPVC
Fathead_Minnow             TLKSWKGLDMPIFS-DDESLFEESILETLLQDLTSSPPLSPTHSYSSHSSSPSS---PEC
Zebrafish                  PLKSWKGLDLPIFQ-DDESLFEESVLETLLQDLSSSPPLSPTPSSSSHSSPPSSPSTPEC
Common_Carp                PLKSWKGLDLPIFP-DDDSLFEESVLETLLQDLTSSVPLSPTPSSYSHSSTPSSPSSPEC
Ray_Finned_Fish            PLKSWKGLDLPIFP-DDDSLFEESVLETLLQDLTSSAPLSPTLSSYSHSSPPSSPSSPEC
Channel_Catfish            PVKSWRGLDLPIFP-DDDSLFEESVLETIFQDL-SSPSLSSTPS--SPSSPPSSPPTPEC
Mexican_TetraAstyanax      PVKSWRGLDLPIFP-DDDSLFEESVLETLLKDL-SSPSLSPTPS--SPSSPPCSPLTPEC
Red_Bellied_Piranha        PVKTWRGLDLPIFP-DDDSLFEESVLETLLKDL-SSPSLSPTPS--SPSSSPSSPPTPEC
                           .:* *.***:*:*  **:******:**::::*: :. .**.: *       *.*   * *

Atlantic_Salmon            WHSPSHFEGVS-----HFCSVQSAHCYPTARCGATLAG-EARAMAEWEGLGEEPMEIEVA
Fathead_Minnow             WCPPLHFDGTSAVSASHFCSVQSAHCNNEAGRGAMMSPVNADNMADGKAAGEVAMETEVA
Zebrafish                  WCPSLHFDGVSAVSAGHFCSVQSAHCNNEAGRGAMMSPVNAGNMTDTKAAGEVPMETDVA
Common_Carp                WCPPLHFDGVSAVSAGQFCSVQSAHCNNEAGRGAMMSPVNTGNMADGKAAGEVAMETEVA
Ray_Finned_Fish            WCPTLHFDGVSAVSAGHFCSVQSAHCNNEAGRGAMMSPVNTSSMADGKAAGEVAMETEVA
Channel_Catfish            WHPPLYFDRVSTMSAGHFCSVQSAHSNHAAGCGATLSPVNKGDIVDGKAAGEVAMETGVV
Mexican_TetraAstyanax      WCPPLHFDGVSAVSAGHFCSVQSAHCNHAAGCGAMMSPLNVGDMTDGKVAGEVAMETEVA
Red_Bellied_Piranha        WRPPLHFDGVSAVSAGHFCSVQSAHCNHAAGCGAMMSPINAGDMADGKAAGEIAMETEVV
                           * .. :*: .*     :********.   *  ** ::  :   :.: :  ** .**  *.

Atlantic_Salmon            SSPLSSCSSIPASPPLRLTA
Fathead_Minnow             SSPLF--MGIPTSPPLQLTV
Zebrafish                  SSPLF--TGIPTSPPLQLTA
Common_Carp                SSPLF--TGIPTSPPLQLT-
Ray_Finned_Fish            SSPLF--MGIPTSPSLQLTA
Channel_Catfish            SSPLS--TSIPASPPLQLTA
Mexican_TetraAstyanax      SSPLS--TGIPASPPLQLTA
Red_Bellied_Piranha        SSPLS--TSIPASPPLQLTA
                           ****    .**:**.*.** 
