---
title: "BIMM143 Structural Bioinformatics"
author: "Jacob Gerzenshtein"
date: "May 10, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Doing Structural Bioinformatics

Loading Bio3D

```{r}
library(bio3d)

file.name <- get.pdb ("1HSG")
```

Reading the PDB, initializing to hiv

```{r}
hiv <- read.pdb(file.name)

```


```{r}
summary(hiv)
```

Trimming the file 

```{r}
prot <- trim.pdb(hiv, "protein")
lig <- trim.pdb(hiv, "ligand")

write.pdb(prot, file = "1HSG_protein.pdb")
write.pdb(lig, file = "1HSG_ligand.pdb")
```



Running ligand and protein

```{r}
library(bio3d)

res <- read.pdb("all.pdbqt", multi = TRUE)

write.pdb(res, "results.pdb")
```

Looking at the Root Mean Square Distance of each docking result to find the best one

```{r}
res <- read.pdb("all.pdbqt", multi = TRUE)

ori <- read.pdb("1HSG_ligand.pdbqt")

rmsd(ori, res)


```

```{r}
res2 <- read.pdb("all.pdbqt")

ori2 <- read.pdb("1HSG_ligand.pdbqt")

res3 <- atom.select(res2, "noh", inverse = TRUE, verbose = TRUE)

ori3 <- atom.select(ori2, "noh", inverse = TRUE, verbose = TRUE)

rmsd(ori3, res3)
```

